name: CI Workflow

permissions:
  issues: read
  contents: read
  actions: read
  security-events: write
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

jobs:
  build:
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-build-test.yml@main
    secrets: inherit

  sast:
    needs: build
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-sast.yml@main
    secrets: inherit

  docker:
    needs: build
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-docker.yml@main
    with:
      project_name: product-service
    secrets: inherit

  sca:
    needs: docker
    uses: PhumlaniDev/reusable-workflows/.github/workflows/java-maven-sca.yml@main
    with:
      image_tag: ${{ needs.docker.outputs.image_tag }}
      project_name: product-service
    secrets: inherit

  #  dast:
  #    needs: build
  #    name: Dynamic Application Security Testing (DAST)
  #    uses: PhumlaniDev/reusable-workflows/.github/workflows/dast.yml@main
  #    secrets:
  #      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  #    with:
  #      image-tag: '${{ secrets.DOCKERHUB_USERNAME }}/infinity-product-service:latest'

  notify:
    uses: PhumlaniDev/reusable-workflows/.github/workflows/discord-notify.yml@main
    needs:
      - build
      - sast
      - sca
      - docker
    if: always()
    with:
      status: >-
        ${{ (needs.build.result == 'success' && needs.sast.result == 'success' && needs.sca.result == 'success' && needs.docker.result == 'success') && 'success' || 'failure' }}
      title: "🚀 Workflow Run - Combined Status"
      description: |
        Build: `${{ needs.build.result }}`
        SAST: `${{ needs.sast.result }}`
        SCA: `${{ needs.sca.result }}`
        Docker: `${{ needs.docker.result }}`
        Commit: `${{ github.sha }}`
        [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
      color: >-
        ${{ (needs.build.result == 'success' && needs.sast.result == 'success' && needs.sca.result == 'success' && needs.docker.result == 'success') && '3066993' || '15158332' }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}